image: "python:3.8"

before_script:
  - git clean -fd
  - python3 --version
  - pip3 install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8